qbmove_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
qbmove_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - qbmove_shaft_joint
    - qbmove_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    qbmove_shaft_joint:
      trajectory: 0.05
      goal: 0.01
    qbmove_stiffness_preset_virtual_joint:
      trajectory: 0.05
      goal: 0.01
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
qbmove_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - qbmove_motor_1_joint
    - qbmove_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    qbmove_motor_1_joint:
      trajectory: 0.05
      goal: 0.01
    qbmove_motor_2_joint:
      trajectory: 0.05
      goal: 0.01
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0